---
# tasks file for ca-server
#- name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
#copy: content="hello ca-server\n" dest=/tmp/ca-server.txt

# - name: "ensure openssl is installed"
#   apt: 
#       name: python 
#       state: latest

- name: "configuring locales"
  shell: export LANGUAGE="en_US.UTF-8" && echo 'LANGUAGE="en_US.UTF-8"' >> /etc/default/locale && echo 'LC_ALL="en_US.UTF-8"' >> /etc/default/locale

# tasks file for ansible-role-ca
- include_vars: "{{ ansible_os_family }}.yml"

- name: "set ca_subject var"
  set_fact:
    ca_subject: '/CN={{ ca_commonname }}'
  when: ca_subject is not defined

- debug: var=ca_subject

- import_tasks: ca-validations.yml
  #when: (ca_force_create is undefined) and (inventory_hostsname == hostvars[groups['infra-instances'][0]]['inventory_hostname'])

- import_tasks: ca-conf.yml
  when: ca_init is defined and ca_force_create == true # defaults to false ...

- import_tasks: ca-key_n_cert.yml
  when: ca_init is defined and ca_force_create == true # defaults to false ...

- import_tasks: certify_nodes.yml
  when: ca_certify_nodes is defined and ca_force_certify_nodes # defaults to false ...

- import_tasks: wildcard_cert.yml
  when: ca_wildcard is defined

- import_tasks: fetch_keys.yml
  when: ca_fetch_keys is defined

- import_tasks: distribute_keys.yml
  when: ca_distribute_keys is defined
